nelmio_api_doc:
    documentation:
        info:
            title: Ecogarden API
            description: This app allow to know the weather in your place !
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
